export default [
  {
    weight: 110,
    key: 'validate.minLength',
    label: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_MIN_LENGTH_LABEL',
    placeholder: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_MIN_LENGTH_PLACEHOLDER',
    type: 'number',
    tooltip: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_MIN_LENGTH_TOOLTIP',
    input: true,
    nullValueIsZero: false,
  },
  {
    weight: 120,
    key: 'validate.maxLength',
    label: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_MAX_LENGTH_LABEL',
    placeholder: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_MAX_LENGTH_PLACEHOLDER',
    type: 'number',
    tooltip: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_MAX_LENGTH_TOOLTIP',
    input: true,
    nullValueIsZero: false,
  },
  {
    weight: 130,
    key: 'validate.pattern',
    label: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_PATTERN_LABEL',
    placeholder: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_PATTERN_PLACEHOLDER',
    type: 'textfield',
    tooltip: 'EDIT_FORM.TEXT_FIELD_VALIDATION.VALIDATE_PATTERN_TOOLTIP',
    input: true,
  },
];
